# AUTO-GENERATED by @clamator/codegen v0.1.3 from engine-to-api.ts.
# DO NOT EDIT. Re-run codegen to update.
from __future__ import annotations
from abc import ABC, abstractmethod
from clamator_protocol import ClamatorClient, Contract, MethodEntry

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class BlockLaunchesParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launch_filter: dict[str, Any] = Field(..., alias="launchFilter")
    reason: str | None = None


class BlockLaunchesResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]


class BlockLaunchesResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["invalid-filter"]


class BlockLaunchesResult(RootModel[BlockLaunchesResult1 | BlockLaunchesResult2]):
    root: BlockLaunchesResult1 | BlockLaunchesResult2


class CancelParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_id: str = Field(..., alias="processId", min_length=1)


class Status(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    state: Literal[
        "idle",
        "scheduled",
        "running",
        "done",
        "failed",
        "cancel_requested",
        "cancelling",
        "cancelled",
    ]
    error: str | None = None
    running_since: AwareDatetime | None = Field(None, alias="runningSince")
    done_at: AwareDatetime | None = Field(None, alias="doneAt")
    duration: float | None = None
    failed_at: AwareDatetime | None = Field(None, alias="failedAt")
    stopped_at: AwareDatetime | None = Field(None, alias="stoppedAt")


class Percent(RootModel[float]):
    root: float = Field(..., ge=0.0, le=100.0)


class Progress(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    percent: Percent | None
    message: str | None = None


class LogItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    timestamp: AwareDatetime
    level: Literal["event", "info", "debug", "warning", "error"]
    message: str
    data: dict[str, Any] | None = None


class Process(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_id: str = Field(..., alias="_id", pattern="^[a-f\\d]{24}$")
    process_id: str = Field(..., alias="processId")
    name: str
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    parent_id: str | None = Field(None, alias="parentId", pattern="^[a-f\\d]{24}$")
    root_id: str = Field(..., alias="rootId", pattern="^[a-f\\d]{24}$")
    depth: int = Field(..., ge=0)
    order: int = Field(..., ge=0)
    cancellable: bool
    special: bool | None = None
    warning: str | None = None
    description: str | None = None
    status: Status
    progress: Progress
    log: list[LogItem]
    ui_widget: str | None = Field(None, alias="uiWidget")
    widget_data: Any | None = Field(None, alias="widgetData")
    supports_resume: bool | None = Field(None, alias="supportsResume")
    has_saved_state: bool | None = Field(None, alias="hasSavedState")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class CancelResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    process: Process


class CancelResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["not-found", "not-cancellable"]


class CancelResult(RootModel[CancelResult1 | CancelResult2]):
    root: CancelResult1 | CancelResult2


class DismissParams(CancelParams):
    pass


class Progress1(Progress):
    pass


class Process1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_id: str = Field(..., alias="_id", pattern="^[a-f\\d]{24}$")
    process_id: str = Field(..., alias="processId")
    name: str
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    parent_id: str | None = Field(None, alias="parentId", pattern="^[a-f\\d]{24}$")
    root_id: str = Field(..., alias="rootId", pattern="^[a-f\\d]{24}$")
    depth: int = Field(..., ge=0)
    order: int = Field(..., ge=0)
    cancellable: bool
    special: bool | None = None
    warning: str | None = None
    description: str | None = None
    status: Status
    progress: Progress1
    log: list[LogItem]
    ui_widget: str | None = Field(None, alias="uiWidget")
    widget_data: Any | None = Field(None, alias="widgetData")
    supports_resume: bool | None = Field(None, alias="supportsResume")
    has_saved_state: bool | None = Field(None, alias="hasSavedState")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class DismissResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    process: Process1


class DismissResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["not-found", "not-dismissable"]


class DismissResult(RootModel[DismissResult1 | DismissResult2]):
    root: DismissResult1 | DismissResult2


class GroupCancelParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata_filter: dict[str, Any] = Field(..., alias="metadataFilter")
    block_new_launches: bool | None = Field(None, alias="blockNewLaunches")
    persist: bool | None = None
    reason: str | None = None


class GroupCancelResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    cancelled_count: int = Field(..., alias="cancelledCount", ge=0)


class GroupCancelResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["invalid-persist-without-block"]


class GroupCancelResult(RootModel[GroupCancelResult1 | GroupCancelResult2]):
    root: GroupCancelResult1 | GroupCancelResult2


class GroupCancelAndWaitParams(GroupCancelParams):
    pass


class GroupCancelAndWaitResult1(GroupCancelResult1):
    pass


class GroupCancelAndWaitResult2(GroupCancelResult2):
    pass


class GroupCancelAndWaitResult(
    RootModel[GroupCancelAndWaitResult1 | GroupCancelAndWaitResult2]
):
    root: GroupCancelAndWaitResult1 | GroupCancelAndWaitResult2


class LaunchParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_id: str = Field(..., alias="processId", min_length=1)
    resume: bool | None = None


class Progress2(Progress):
    pass


class Process2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_id: str = Field(..., alias="_id", pattern="^[a-f\\d]{24}$")
    process_id: str = Field(..., alias="processId")
    name: str
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    parent_id: str | None = Field(None, alias="parentId", pattern="^[a-f\\d]{24}$")
    root_id: str = Field(..., alias="rootId", pattern="^[a-f\\d]{24}$")
    depth: int = Field(..., ge=0)
    order: int = Field(..., ge=0)
    cancellable: bool
    special: bool | None = None
    warning: str | None = None
    description: str | None = None
    status: Status
    progress: Progress2
    log: list[LogItem]
    ui_widget: str | None = Field(None, alias="uiWidget")
    widget_data: Any | None = Field(None, alias="widgetData")
    supports_resume: bool | None = Field(None, alias="supportsResume")
    has_saved_state: bool | None = Field(None, alias="hasSavedState")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class LaunchResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    process: Process2


class LaunchResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal[
        "not-found", "not-launchable", "no-resume-support", "launch-blocked"
    ]


class LaunchResult(RootModel[LaunchResult1 | LaunchResult2]):
    root: LaunchResult1 | LaunchResult2


class ResyncParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clean: bool | None = None
    metadata_filter: dict[str, Any] | None = Field(None, alias="metadataFilter")


class UnblockLaunchesParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launch_filter: dict[str, Any] = Field(..., alias="launchFilter")


class UnblockLaunchesResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removed: int = Field(..., ge=0)

class EngineClient:
    def __init__(self, client: ClamatorClient) -> None:
        self._client = client

    async def block_launches(self, params: BlockLaunchesParams) -> BlockLaunchesResult:
        raw = await self._client.call("engine", "blockLaunches", params.model_dump(by_alias=True))
        return BlockLaunchesResult.model_validate(raw)

    async def cancel(self, params: CancelParams) -> CancelResult:
        raw = await self._client.call("engine", "cancel", params.model_dump(by_alias=True))
        return CancelResult.model_validate(raw)

    async def dismiss(self, params: DismissParams) -> DismissResult:
        raw = await self._client.call("engine", "dismiss", params.model_dump(by_alias=True))
        return DismissResult.model_validate(raw)

    async def group_cancel(self, params: GroupCancelParams) -> GroupCancelResult:
        raw = await self._client.call("engine", "groupCancel", params.model_dump(by_alias=True))
        return GroupCancelResult.model_validate(raw)

    async def group_cancel_and_wait(self, params: GroupCancelAndWaitParams) -> GroupCancelAndWaitResult:
        raw = await self._client.call("engine", "groupCancelAndWait", params.model_dump(by_alias=True))
        return GroupCancelAndWaitResult.model_validate(raw)

    async def launch(self, params: LaunchParams) -> LaunchResult:
        raw = await self._client.call("engine", "launch", params.model_dump(by_alias=True))
        return LaunchResult.model_validate(raw)

    async def resync(self, params: ResyncParams) -> None:
        await self._client.notify("engine", "resync", params.model_dump(by_alias=True))

    async def unblock_launches(self, params: UnblockLaunchesParams) -> UnblockLaunchesResult:
        raw = await self._client.call("engine", "unblockLaunches", params.model_dump(by_alias=True))
        return UnblockLaunchesResult.model_validate(raw)


class EngineService(ABC):
    @abstractmethod
    async def block_launches(self, params: BlockLaunchesParams) -> BlockLaunchesResult: ...

    @abstractmethod
    async def cancel(self, params: CancelParams) -> CancelResult: ...

    @abstractmethod
    async def dismiss(self, params: DismissParams) -> DismissResult: ...

    @abstractmethod
    async def group_cancel(self, params: GroupCancelParams) -> GroupCancelResult: ...

    @abstractmethod
    async def group_cancel_and_wait(self, params: GroupCancelAndWaitParams) -> GroupCancelAndWaitResult: ...

    @abstractmethod
    async def launch(self, params: LaunchParams) -> LaunchResult: ...

    @abstractmethod
    async def resync(self, params: ResyncParams) -> None: ...

    @abstractmethod
    async def unblock_launches(self, params: UnblockLaunchesParams) -> UnblockLaunchesResult: ...


METHODS = {
    "blockLaunches": MethodEntry(params_model=BlockLaunchesParams, result_model=BlockLaunchesResult, handler_attr="block_launches"),
    "cancel": MethodEntry(params_model=CancelParams, result_model=CancelResult, handler_attr="cancel"),
    "dismiss": MethodEntry(params_model=DismissParams, result_model=DismissResult, handler_attr="dismiss"),
    "groupCancel": MethodEntry(params_model=GroupCancelParams, result_model=GroupCancelResult, handler_attr="group_cancel"),
    "groupCancelAndWait": MethodEntry(params_model=GroupCancelAndWaitParams, result_model=GroupCancelAndWaitResult, handler_attr="group_cancel_and_wait"),
    "launch": MethodEntry(params_model=LaunchParams, result_model=LaunchResult, handler_attr="launch"),
    "resync": MethodEntry(params_model=ResyncParams, result_model=None, handler_attr="resync"),
    "unblockLaunches": MethodEntry(params_model=UnblockLaunchesParams, result_model=UnblockLaunchesResult, handler_attr="unblock_launches"),
}

engine_contract = Contract(
    service="engine",
    methods=METHODS,
)
