# AUTO-GENERATED by @clamator/codegen v0.1.9 from optio-engine-to-api.ts.
# DO NOT EDIT. Re-run codegen to update.
from __future__ import annotations
from abc import ABC, abstractmethod
from clamator_protocol import ClamatorClient, Contract, MethodEntry

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class LaunchFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    and_: list[Any] = Field(..., alias="AND", min_length=1)


class LaunchFilter1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    or_: list[Any] = Field(..., alias="OR", min_length=1)


class LaunchFilter2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    not_: Any = Field(..., alias="NOT")


class LaunchFilter3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    eq: str | float | bool | None = None
    ne: str | float | bool | None = None
    in_: list[str | float | bool | None] | None = Field(None, alias="in")
    nin: list[str | float | bool | None] | None = None
    exists: bool | None = None
    gt: str | float | bool | None = None
    gte: str | float | bool | None = None
    lt: str | float | bool | None = None
    lte: str | float | bool | None = None


class BlockLaunchesParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launch_filter: (
        LaunchFilter
        | LaunchFilter1
        | LaunchFilter2
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), LaunchFilter3]
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), str | float | bool | None]
    ) = Field(..., alias="launchFilter")
    reason: str | None = None


class BlockLaunchesResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]


class BlockLaunchesResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["invalid-filter"]


class BlockLaunchesResult(RootModel[BlockLaunchesResult1 | BlockLaunchesResult2]):
    root: BlockLaunchesResult1 | BlockLaunchesResult2


class CancelParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_id: str = Field(..., alias="processId", min_length=1)


class Status(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    state: Literal[
        "idle",
        "scheduled",
        "running",
        "done",
        "failed",
        "cancel_requested",
        "cancelling",
        "cancelled",
    ]
    error: str | None = None
    running_since: AwareDatetime | None = Field(None, alias="runningSince")
    done_at: AwareDatetime | None = Field(None, alias="doneAt")
    duration: float | None = None
    failed_at: AwareDatetime | None = Field(None, alias="failedAt")
    stopped_at: AwareDatetime | None = Field(None, alias="stoppedAt")


class Percent(RootModel[float]):
    root: float = Field(..., ge=0.0, le=100.0)


class Progress(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    percent: Percent | None
    message: str | None = None


class LogItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    timestamp: AwareDatetime
    level: Literal["event", "info", "debug", "warning", "error"]
    message: str
    data: dict[str, Any] | None = None


class BrowserOpenRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    request_id: str = Field(..., alias="requestId")
    url: str
    created_at: AwareDatetime | None = Field(None, alias="createdAt")


class SessionEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    request_id: str = Field(..., alias="requestId")
    type: Literal["attention"]
    reason: str


class SessionEvents1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    request_id: str = Field(..., alias="requestId")
    type: Literal["client"]
    keyword: str
    data: Any | None = None


class Process(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_id: str = Field(..., alias="_id", pattern="^[a-f\\d]{24}$")
    process_id: str = Field(..., alias="processId")
    name: str
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    parent_id: str | None = Field(None, alias="parentId", pattern="^[a-f\\d]{24}$")
    root_id: str = Field(..., alias="rootId", pattern="^[a-f\\d]{24}$")
    depth: int = Field(..., ge=0)
    order: int = Field(..., ge=0)
    cancellable: bool
    special: bool | None = None
    warning: str | None = None
    description: str | None = None
    status: Status
    progress: Progress
    log: list[LogItem]
    ui_widget: str | None = Field(None, alias="uiWidget")
    widget_data: Any | None = Field(None, alias="widgetData")
    supports_resume: bool | None = Field(None, alias="supportsResume")
    has_saved_state: bool | None = Field(None, alias="hasSavedState")
    auto_resume_scheduled: bool | None = Field(None, alias="autoResumeScheduled")
    browser_open_requests: list[BrowserOpenRequest] | None = Field(
        None, alias="browserOpenRequests"
    )
    session_events: list[SessionEvents | SessionEvents1] | None = Field(
        None, alias="sessionEvents"
    )
    originating_session_id: str | None = Field(None, alias="originatingSessionId")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class CancelResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    process: Process


class CancelResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["not-found", "not-cancellable"]


class CancelResult(RootModel[CancelResult1 | CancelResult2]):
    root: CancelResult1 | CancelResult2


class DismissParams(CancelParams):
    pass


class Progress1(Progress):
    pass


class SessionEvents2(SessionEvents):
    pass


class SessionEvents3(SessionEvents1):
    pass


class Process1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_id: str = Field(..., alias="_id", pattern="^[a-f\\d]{24}$")
    process_id: str = Field(..., alias="processId")
    name: str
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    parent_id: str | None = Field(None, alias="parentId", pattern="^[a-f\\d]{24}$")
    root_id: str = Field(..., alias="rootId", pattern="^[a-f\\d]{24}$")
    depth: int = Field(..., ge=0)
    order: int = Field(..., ge=0)
    cancellable: bool
    special: bool | None = None
    warning: str | None = None
    description: str | None = None
    status: Status
    progress: Progress1
    log: list[LogItem]
    ui_widget: str | None = Field(None, alias="uiWidget")
    widget_data: Any | None = Field(None, alias="widgetData")
    supports_resume: bool | None = Field(None, alias="supportsResume")
    has_saved_state: bool | None = Field(None, alias="hasSavedState")
    auto_resume_scheduled: bool | None = Field(None, alias="autoResumeScheduled")
    browser_open_requests: list[BrowserOpenRequest] | None = Field(
        None, alias="browserOpenRequests"
    )
    session_events: list[SessionEvents2 | SessionEvents3] | None = Field(
        None, alias="sessionEvents"
    )
    originating_session_id: str | None = Field(None, alias="originatingSessionId")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class DismissResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    process: Process1


class DismissResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["not-found", "not-dismissable"]


class DismissResult(RootModel[DismissResult1 | DismissResult2]):
    root: DismissResult1 | DismissResult2


class MetadataFilter(LaunchFilter):
    pass


class MetadataFilter1(LaunchFilter1):
    pass


class MetadataFilter2(LaunchFilter2):
    pass


class MetadataFilter3(LaunchFilter3):
    pass


class GroupCancelParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata_filter: (
        MetadataFilter
        | MetadataFilter1
        | MetadataFilter2
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), MetadataFilter3]
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), str | float | bool | None]
    ) = Field(..., alias="metadataFilter")
    block_new_launches: bool | None = Field(None, alias="blockNewLaunches")
    persist: bool | None = None
    reason: str | None = None
    purge_records: bool | None = Field(None, alias="purgeRecords")


class GroupCancelResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    cancelled_count: int = Field(..., alias="cancelledCount", ge=0)


class GroupCancelResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["invalid-persist-without-block"]


class GroupCancelResult(RootModel[GroupCancelResult1 | GroupCancelResult2]):
    root: GroupCancelResult1 | GroupCancelResult2


class MetadataFilter4(LaunchFilter):
    pass


class MetadataFilter5(LaunchFilter1):
    pass


class MetadataFilter6(LaunchFilter2):
    pass


class MetadataFilter7(LaunchFilter3):
    pass


class GroupCancelAndWaitParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata_filter: (
        MetadataFilter4
        | MetadataFilter5
        | MetadataFilter6
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), MetadataFilter7]
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), str | float | bool | None]
    ) = Field(..., alias="metadataFilter")
    block_new_launches: bool | None = Field(None, alias="blockNewLaunches")
    persist: bool | None = None
    reason: str | None = None
    purge_records: bool | None = Field(None, alias="purgeRecords")


class GroupCancelAndWaitResult1(GroupCancelResult1):
    pass


class GroupCancelAndWaitResult2(GroupCancelResult2):
    pass


class GroupCancelAndWaitResult(
    RootModel[GroupCancelAndWaitResult1 | GroupCancelAndWaitResult2]
):
    root: GroupCancelAndWaitResult1 | GroupCancelAndWaitResult2


class LaunchParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_id: str = Field(..., alias="processId", min_length=1)
    resume: bool | None = None
    session_id: str | None = Field(..., alias="sessionId")


class Progress2(Progress):
    pass


class SessionEvents4(SessionEvents):
    pass


class SessionEvents5(SessionEvents1):
    pass


class Process2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_id: str = Field(..., alias="_id", pattern="^[a-f\\d]{24}$")
    process_id: str = Field(..., alias="processId")
    name: str
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    parent_id: str | None = Field(None, alias="parentId", pattern="^[a-f\\d]{24}$")
    root_id: str = Field(..., alias="rootId", pattern="^[a-f\\d]{24}$")
    depth: int = Field(..., ge=0)
    order: int = Field(..., ge=0)
    cancellable: bool
    special: bool | None = None
    warning: str | None = None
    description: str | None = None
    status: Status
    progress: Progress2
    log: list[LogItem]
    ui_widget: str | None = Field(None, alias="uiWidget")
    widget_data: Any | None = Field(None, alias="widgetData")
    supports_resume: bool | None = Field(None, alias="supportsResume")
    has_saved_state: bool | None = Field(None, alias="hasSavedState")
    auto_resume_scheduled: bool | None = Field(None, alias="autoResumeScheduled")
    browser_open_requests: list[BrowserOpenRequest] | None = Field(
        None, alias="browserOpenRequests"
    )
    session_events: list[SessionEvents4 | SessionEvents5] | None = Field(
        None, alias="sessionEvents"
    )
    originating_session_id: str | None = Field(None, alias="originatingSessionId")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class LaunchResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    process: Process2


class LaunchResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal[
        "not-found", "not-launchable", "no-resume-support", "launch-blocked"
    ]


class LaunchResult(RootModel[LaunchResult1 | LaunchResult2]):
    root: LaunchResult1 | LaunchResult2


class MaterializeUploadParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_id: str = Field(..., alias="processId", min_length=1)
    blob_id: str = Field(..., alias="blobId")
    filename: str


class MaterializeUploadResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    path: str


class MaterializeUploadResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: str


class MaterializeUploadResult(
    RootModel[MaterializeUploadResult1 | MaterializeUploadResult2]
):
    root: MaterializeUploadResult1 | MaterializeUploadResult2


class MetadataFilter8(LaunchFilter):
    pass


class MetadataFilter9(LaunchFilter1):
    pass


class MetadataFilter10(LaunchFilter2):
    pass


class MetadataFilter11(LaunchFilter3):
    pass


class ResyncParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clean: bool | None = None
    metadata_filter: (
        MetadataFilter8
        | MetadataFilter9
        | MetadataFilter10
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), MetadataFilter11]
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), str | float | bool | None]
        | None
    ) = Field(None, alias="metadataFilter")


class LaunchFilter4(LaunchFilter):
    pass


class LaunchFilter5(LaunchFilter1):
    pass


class LaunchFilter6(LaunchFilter2):
    pass


class LaunchFilter7(LaunchFilter3):
    pass


class UnblockLaunchesParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    launch_filter: (
        LaunchFilter4
        | LaunchFilter5
        | LaunchFilter6
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), LaunchFilter7]
        | dict[constr(pattern=r"^[^.$]+(\.[^.$]+)*$"), str | float | bool | None]
    ) = Field(..., alias="launchFilter")


class UnblockLaunchesResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removed: int = Field(..., ge=0)


class OptioEngineClient:
    def __init__(self, client: ClamatorClient) -> None:
        self._client = client

    async def block_launches(self, params: BlockLaunchesParams, *, timeout_ms: int | None = None) -> BlockLaunchesResult:
        raw = await self._client.call("optio-engine", "blockLaunches", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return BlockLaunchesResult.model_validate(raw)

    async def cancel(self, params: CancelParams, *, timeout_ms: int | None = None) -> CancelResult:
        raw = await self._client.call("optio-engine", "cancel", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return CancelResult.model_validate(raw)

    async def dismiss(self, params: DismissParams, *, timeout_ms: int | None = None) -> DismissResult:
        raw = await self._client.call("optio-engine", "dismiss", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return DismissResult.model_validate(raw)

    async def group_cancel(self, params: GroupCancelParams, *, timeout_ms: int | None = None) -> GroupCancelResult:
        raw = await self._client.call("optio-engine", "groupCancel", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return GroupCancelResult.model_validate(raw)

    async def group_cancel_and_wait(self, params: GroupCancelAndWaitParams, *, timeout_ms: int | None = None) -> GroupCancelAndWaitResult:
        raw = await self._client.call("optio-engine", "groupCancelAndWait", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return GroupCancelAndWaitResult.model_validate(raw)

    async def launch(self, params: LaunchParams, *, timeout_ms: int | None = None) -> LaunchResult:
        raw = await self._client.call("optio-engine", "launch", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return LaunchResult.model_validate(raw)

    async def materialize_upload(self, params: MaterializeUploadParams, *, timeout_ms: int | None = None) -> MaterializeUploadResult:
        raw = await self._client.call("optio-engine", "materializeUpload", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return MaterializeUploadResult.model_validate(raw)

    async def resync(self, params: ResyncParams) -> None:
        await self._client.notify("optio-engine", "resync", params.model_dump(mode='json', by_alias=True))

    async def unblock_launches(self, params: UnblockLaunchesParams, *, timeout_ms: int | None = None) -> UnblockLaunchesResult:
        raw = await self._client.call("optio-engine", "unblockLaunches", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return UnblockLaunchesResult.model_validate(raw)


class OptioEngineService(ABC):
    @abstractmethod
    async def block_launches(self, params: BlockLaunchesParams) -> BlockLaunchesResult: ...

    @abstractmethod
    async def cancel(self, params: CancelParams) -> CancelResult: ...

    @abstractmethod
    async def dismiss(self, params: DismissParams) -> DismissResult: ...

    @abstractmethod
    async def group_cancel(self, params: GroupCancelParams) -> GroupCancelResult: ...

    @abstractmethod
    async def group_cancel_and_wait(self, params: GroupCancelAndWaitParams) -> GroupCancelAndWaitResult: ...

    @abstractmethod
    async def launch(self, params: LaunchParams) -> LaunchResult: ...

    @abstractmethod
    async def materialize_upload(self, params: MaterializeUploadParams) -> MaterializeUploadResult: ...

    @abstractmethod
    async def resync(self, params: ResyncParams) -> None: ...

    @abstractmethod
    async def unblock_launches(self, params: UnblockLaunchesParams) -> UnblockLaunchesResult: ...


METHODS = {
    "blockLaunches": MethodEntry(params_model=BlockLaunchesParams, result_model=BlockLaunchesResult, handler_attr="block_launches"),
    "cancel": MethodEntry(params_model=CancelParams, result_model=CancelResult, handler_attr="cancel"),
    "dismiss": MethodEntry(params_model=DismissParams, result_model=DismissResult, handler_attr="dismiss"),
    "groupCancel": MethodEntry(params_model=GroupCancelParams, result_model=GroupCancelResult, handler_attr="group_cancel"),
    "groupCancelAndWait": MethodEntry(params_model=GroupCancelAndWaitParams, result_model=GroupCancelAndWaitResult, handler_attr="group_cancel_and_wait"),
    "launch": MethodEntry(params_model=LaunchParams, result_model=LaunchResult, handler_attr="launch"),
    "materializeUpload": MethodEntry(params_model=MaterializeUploadParams, result_model=MaterializeUploadResult, handler_attr="materialize_upload"),
    "resync": MethodEntry(params_model=ResyncParams, result_model=None, handler_attr="resync"),
    "unblockLaunches": MethodEntry(params_model=UnblockLaunchesParams, result_model=UnblockLaunchesResult, handler_attr="unblock_launches"),
}

optio_engine_contract = Contract(
    service="optio-engine",
    methods=METHODS,
)
