// AUTO-GENERATED by scripts/generate.py from optio_agents_all.AGENTS. DO NOT EDIT.
// Regenerate with `make codegen`.

import type { AgentInfo } from './agent-info.js';

export type AgentType = 'antigravity' | 'claudecode' | 'codex' | 'cursor' | 'grok' | 'kimicode' | 'opencode';

export const AGENTS: Record<AgentType, AgentInfo> = {
  antigravity: { slug: 'antigravity', name: "Antigravity CLI", url: "https://antigravity.google" },
  claudecode: { slug: 'claudecode', name: "Claude Code", url: "https://claude.com/product/claude-code" },
  codex: { slug: 'codex', name: "Codex", url: "https://openai.com/codex" },
  cursor: { slug: 'cursor', name: "Cursor CLI", url: "https://cursor.com/cli" },
  grok: { slug: 'grok', name: "Grok Build", url: "https://x.ai/cli" },
  kimicode: { slug: 'kimicode', name: "Kimi Code", url: "https://www.kimi.com/coding" },
  opencode: { slug: 'opencode', name: "OpenCode", url: "https://opencode.ai" },
};
