#!/usr/bin/env python3
"""Generate optio-agents-ui/src/agents.generated.ts from the Python AGENTS SSOT.

Run via `make codegen`. The output is committed; never edit it by hand.
"""
from __future__ import annotations

import json
from pathlib import Path

from optio_agents_all import AGENTS

OUT = Path(__file__).resolve().parent.parent / "src" / "agents.generated.ts"

HEADER = (
    "// AUTO-GENERATED by scripts/generate.py from optio_agents_all.AGENTS. DO NOT EDIT.\n"
    "// Regenerate with `make codegen`.\n\n"
)


def main() -> None:
    slugs = sorted(AGENTS.keys())
    union = " | ".join(f"'{s}'" for s in slugs)
    parts = [HEADER]
    parts.append("import type { AgentInfo } from './agent-info.js';\n\n")
    parts.append(f"export type AgentType = {union};\n\n")
    parts.append("export const AGENTS: Record<AgentType, AgentInfo> = {\n")
    for s in slugs:
        info = AGENTS[s]
        parts.append(
            f"  {s}: {{ slug: '{s}', name: {json.dumps(info.name)}, url: {json.dumps(info.url)} }},\n"
        )
    parts.append("};\n")
    OUT.write_text("".join(parts))
    print(f"wrote {OUT} ({len(slugs)} engines)")


if __name__ == "__main__":
    main()
