// AUTO-GENERATED by @clamator/codegen v0.1.7 from engine-to-api.ts.
// DO NOT EDIT. Re-run codegen to update.
import { engineContract } from 'optio-contracts/engine-to-api';
import type { ClamatorClient } from '@clamator/protocol';
import type { z } from 'zod';

export type BlockLaunchesParams = z.infer<typeof engineContract.methods.blockLaunches.params>;
export type BlockLaunchesResult = z.infer<typeof engineContract.methods.blockLaunches.result>;
export type CancelParams = z.infer<typeof engineContract.methods.cancel.params>;
export type CancelResult = z.infer<typeof engineContract.methods.cancel.result>;
export type DismissParams = z.infer<typeof engineContract.methods.dismiss.params>;
export type DismissResult = z.infer<typeof engineContract.methods.dismiss.result>;
export type GroupCancelParams = z.infer<typeof engineContract.methods.groupCancel.params>;
export type GroupCancelResult = z.infer<typeof engineContract.methods.groupCancel.result>;
export type GroupCancelAndWaitParams = z.infer<typeof engineContract.methods.groupCancelAndWait.params>;
export type GroupCancelAndWaitResult = z.infer<typeof engineContract.methods.groupCancelAndWait.result>;
export type LaunchParams = z.infer<typeof engineContract.methods.launch.params>;
export type LaunchResult = z.infer<typeof engineContract.methods.launch.result>;
export type ResyncParams = z.infer<typeof engineContract.methods.resync.params>;
export type UnblockLaunchesParams = z.infer<typeof engineContract.methods.unblockLaunches.params>;
export type UnblockLaunchesResult = z.infer<typeof engineContract.methods.unblockLaunches.result>;

export class EngineClient {
  constructor(private client: ClamatorClient) {}
  blockLaunches(params: BlockLaunchesParams, opts?: { timeoutMs?: number }): Promise<BlockLaunchesResult> {
    return this.client.call('engine', 'blockLaunches', params, opts);
  }
  cancel(params: CancelParams, opts?: { timeoutMs?: number }): Promise<CancelResult> {
    return this.client.call('engine', 'cancel', params, opts);
  }
  dismiss(params: DismissParams, opts?: { timeoutMs?: number }): Promise<DismissResult> {
    return this.client.call('engine', 'dismiss', params, opts);
  }
  groupCancel(params: GroupCancelParams, opts?: { timeoutMs?: number }): Promise<GroupCancelResult> {
    return this.client.call('engine', 'groupCancel', params, opts);
  }
  groupCancelAndWait(params: GroupCancelAndWaitParams, opts?: { timeoutMs?: number }): Promise<GroupCancelAndWaitResult> {
    return this.client.call('engine', 'groupCancelAndWait', params, opts);
  }
  launch(params: LaunchParams, opts?: { timeoutMs?: number }): Promise<LaunchResult> {
    return this.client.call('engine', 'launch', params, opts);
  }
  resync(params: ResyncParams): Promise<void> {
    return this.client.notify('engine', 'resync', params);
  }
  unblockLaunches(params: UnblockLaunchesParams, opts?: { timeoutMs?: number }): Promise<UnblockLaunchesResult> {
    return this.client.call('engine', 'unblockLaunches', params, opts);
  }
}

export interface EngineService {
  blockLaunches(params: BlockLaunchesParams, opts?: { timeoutMs?: number }): Promise<BlockLaunchesResult>;
  cancel(params: CancelParams, opts?: { timeoutMs?: number }): Promise<CancelResult>;
  dismiss(params: DismissParams, opts?: { timeoutMs?: number }): Promise<DismissResult>;
  groupCancel(params: GroupCancelParams, opts?: { timeoutMs?: number }): Promise<GroupCancelResult>;
  groupCancelAndWait(params: GroupCancelAndWaitParams, opts?: { timeoutMs?: number }): Promise<GroupCancelAndWaitResult>;
  launch(params: LaunchParams, opts?: { timeoutMs?: number }): Promise<LaunchResult>;
  resync(params: ResyncParams): Promise<void>;
  unblockLaunches(params: UnblockLaunchesParams, opts?: { timeoutMs?: number }): Promise<UnblockLaunchesResult>;
}
